title: User documentation for emuStudio
email: emustudio@googlegroups.com
tagline: User documentation for emuStudio 0.41
description: >- # this means to ignore newlines until "baseurl:"
  User documentation for emuStudio 0.41. emuStudio is universal emulation platform
  and framework targeting mainly academic sphere.
baseurl: "/documentation/user" # the subpath of your site, e.g. /blog
url: ""
github_username: emustudio
ga_tracking: UA-3492956-5
ga_tracking_anonymize_ip: true # Use GDPR compliant Google Analytics settings (true by default)

include:
  - _doc

logo: "/assets/logo-1.svg"
aux_links:
  "Back to website":
    - "/"

# Build settings
markdown: kramdown
theme: "just-the-docs"

destination: ../../documentation/user/

search_enabled: true
search:
  # Split pages into sections that can be searched individually
  # Supports 1 - 6, default: 2
  heading_level: 2
  # Maximum amount of previews per search result
  # Default: 3
  previews: 2
  # Maximum amount of words to display before a matched word in the preview
  # Default: 5
  preview_words_before: 3
  # Maximum amount of words to display after a matched word in the preview
  # Default: 10
  preview_words_after: 3
  # Set the search token separator
  # Default: /[\s\-/]+/
  # Example: enable support for hyphenated search words
  tokenizer_separator: /[\s/]+/
  # Display the relative url in search results
  # Supports true (default) or false
  rel_url: true
  # Enable or disable the search button that appears in the bottom right corner of every page
  # Supports true or false (default)
  button: false

mermaid:
  # Version of mermaid library
  # Pick an available version from https://cdn.jsdelivr.net/npm/mermaid/
  version: "9.1.6"
  # Put any additional configuration, such as setting the theme, in _includes/mermaid_config.js
  # See also docs/ui-components/code
