source 'https://rubygems.org'

gem 'asciidoctor'
gem 'pygments.rb'
gem 'just-the-docs'
gem 'webrick'
gem 'jekyll', '4.2.2'

group :jekyll_plugins do
  gem 'jekyll-sitemap'
  gem 'jekyll-asciidoc'
  gem 'asciidoctor-diagram'
end
