source 'https://rubygems.org'

gem 'asciidoctor'
gem 'pygments.rb'
gem 'just-the-docs', '~> 0.12'
gem 'webrick'
gem 'base64'
gem 'csv'
gem 'jekyll', '~> 4.3'

group :jekyll_plugins do
  gem 'jekyll-sitemap'
  gem 'jekyll-asciidoc'
  gem 'asciidoctor-diagram'
end
