source 'https://rubygems.org'

gem 'asciidoctor'
gem 'pygments.rb'
gem 'just-the-docs', '0.4.0.rc3'
gem 'webrick'
gem 'base64'
gem 'csv'
gem 'jekyll', '4.3.1'

group :jekyll_plugins do
  gem 'jekyll-sitemap'
  gem 'jekyll-asciidoc'
  gem 'asciidoctor-diagram'
end
